service: S3secure # NOTE: update this with your service name


custom:
  stage: ${opt:stage, self:provider.stage}
  region: ${opt:region, self:provider.region}
  secure_host: ${opt:host}

provider:
  name: aws
  runtime: nodejs6.10

  environment:
    SECURE_HOST: ${self:custom.secure_host}

# you can add packaging information here
#package:
#  include:
#    - include-me.js
#    - include-me-dir/**
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**

functions:
  index:
    handler: handler.index
    events:
      - http:
          path: /
          method: get
